spring:
  application:
    name: pos-system-backend

  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

server:
  port: 8080

cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:4200
    - http://localhost:5173